Weapons = {
    UNARMED = GetHashKey("WEAPON_UNARMED"),

    -- Melee
    DAGGER        = GetHashKey("WEAPON_DAGGER"),
    BAT           = GetHashKey("WEAPON_BAT"),
    BOTTLE        = GetHashKey("WEAPON_BOTTLE"),
    CROWBAR       = GetHashKey("WEAPON_CROWBAR"),
    FLASHLIGHT    = GetHashKey("WEAPON_FLASHLIGHT"),
    GOLFCLUB      = GetHashKey("WEAPON_GOLFCLUB"),
    HAMMER        = GetHashKey("WEAPON_HAMMER"),
    HATCHET       = GetHashKey("WEAPON_HATCHET"),
    KNUCKLE       = GetHashKey("WEAPON_KNUCKLE"),
    KNIFE         = GetHashKey("WEAPON_KNIFE"),
    MACHETE       = GetHashKey("WEAPON_MACHETE"),
    SWITCHBLADE   = GetHashKey("WEAPON_SWITCHBLADE"),
    NIGHTSTICK    = GetHashKey("WEAPON_NIGHTSTICK"),
    WRENCH        = GetHashKey("WEAPON_WRENCH"),
    BATTLEAXE     = GetHashKey("WEAPON_BATTLEAXE"),
    POOLCUE       = GetHashKey("WEAPON_POOLCUE"),
    STONE_HATCHET = GetHashKey("WEAPON_STONE_HATCHET"),

    -- Handguns
    PISTOL         = GetHashKey("WEAPON_PISTOL"),
    PISTOL_MK2     = GetHashKey("WEAPON_PISTOL_MK2"),
    COMBATPISTOL   = GetHashKey("WEAPON_COMBATPISTOL"),
    APPISTOL       = GetHashKey("WEAPON_APPISTOL"),
    STUNGUN        = GetHashKey("WEAPON_STUNGUN"),
    PISTOL50       = GetHashKey("WEAPON_PISTOL50"),
    SNSPISTOL      = GetHashKey("WEAPON_SNSPISTOL"),
    SNSPISTOL_MK2  = GetHashKey("WEAPON_SNSPISTOL_MK2"),
    HEAVYPISTOL    = GetHashKey("WEAPON_HEAVYPISTOL"),
    VINTAGEPISTOL  = GetHashKey("WEAPON_VINTAGEPISTOL"),
    FLAREGUN       = GetHashKey("WEAPON_FLAREGUN"),
    MARKSMANPISTOL = GetHashKey("WEAPON_MARKSMANPISTOL"),
    REVOLVER       = GetHashKey("WEAPON_REVOLVER"),
    REVOLVER_MK2   = GetHashKey("WEAPON_REVOLVER_MK2"),
    DOUBLEACTION   = GetHashKey("WEAPON_DOUBLEACTION"),
    RAYPISTOL      = GetHashKey("WEAPON_RAYPISTOL"),
    --CERAMICPISTOL  = GetHashKey("WEAPON_CERAMICPISTOL"), -- Exist in some docs but can't find in game
    --NAVYREVOLVER   = GetHashKey("WEAPON_NAVYREVOLVER"),
    --GADGETPISTOL   = GetHashKey("WEAPON_GADGETPISTOL"),
    --STUNGUN_MP     = GetHashKey("WEAPON_STUNGUN_MP"),

    -- Submachine Guns
    MICROSMG        = GetHashKey("WEAPON_MICROSMG"),
    SMG             = GetHashKey("WEAPON_SMG"),
    SMG_MK2         = GetHashKey("WEAPON_SMG_MK2"),
    ASSAULTSMG      = GetHashKey("WEAPON_ASSAULTSMG"),
    COMBATPDW       = GetHashKey("WEAPON_COMBATPDW"),
    MACHINEPISTOL   = GetHashKey("WEAPON_MACHINEPISTOL"),
    MINISMG         = GetHashKey("WEAPON_MINISMG"),

    -- Shotguns
    PUMPSHOTGUN     = GetHashKey("WEAPON_PUMPSHOTGUN"),
    PUMPSHOTGUN_MK2 = GetHashKey("WEAPON_PUMPSHOTGUN_MK2"),
    SAWNOFFSHOTGUN  = GetHashKey("WEAPON_SAWNOFFSHOTGUN"),
    ASSAULTSHOTGUN  = GetHashKey("WEAPON_ASSAULTSHOTGUN"),
    BULLPUPSHOTGUN  = GetHashKey("WEAPON_BULLPUPSHOTGUN"),
    MUSKET          = GetHashKey("WEAPON_MUSKET"),
    HEAVYSHOTGUN    = GetHashKey("WEAPON_HEAVYSHOTGUN"),
    DBSHOTGUN       = GetHashKey("WEAPON_DBSHOTGUN"),
    AUTOSHOTGUN     = GetHashKey("WEAPON_AUTOSHOTGUN"),
    --COMBATSHOTGUN   = GetHashKey("WEAPON_COMBATSHOTGUN"), -- Exist in some docs but can't find in game

    -- Assault Rifles
    ASSAULTRIFLE       = GetHashKey("WEAPON_ASSAULTRIFLE"),
    ASSAULTRIFLE_MK2   = GetHashKey("WEAPON_ASSAULTRIFLE_MK2"),
    CARBINERIFLE       = GetHashKey("WEAPON_CARBINERIFLE"),
    CARBINERIFLE_MK2   = GetHashKey("WEAPON_CARBINERIFLE_MK2"),
    ADVANCEDRIFLE      = GetHashKey("WEAPON_ADVANCEDRIFLE"),
    SPECIALCARBINE     = GetHashKey("WEAPON_SPECIALCARBINE"),
    SPECIALCARBINE_MK2 = GetHashKey("WEAPON_SPECIALCARBINE_MK2"),
    BULLPUPRIFLE       = GetHashKey("WEAPON_BULLPUPRIFLE"),
    BULLPUPRIFLE_MK2   = GetHashKey("WEAPON_BULLPUPRIFLE_MK2"),
    COMPACTRIFLE       = GetHashKey("WEAPON_COMPACTRIFLE"),
    --MILITARYRIFLE      = GetHashKey("WEAPON_MILITARYRIFLE"), -- Exist in some docs but can't find in game
    --HEAVYRIFLE         = GetHashKey("WEAPON_HEAVYRIFLE"),

    -- Heavy Weapons
    COMPACTLAUNCHER = GetHashKey("WEAPON_COMPACTLAUNCHER"),
    FIREWORK        = GetHashKey("WEAPON_FIREWORK"),
    GRENADELAUNCHER = GetHashKey("WEAPON_GRENADELAUNCHER"),
    HOMINGLAUNCHER  = GetHashKey("WEAPON_HOMINGLAUNCHER"),
    MINIGUN         = GetHashKey("WEAPON_MINIGUN"),
    RAILGUN         = GetHashKey("WEAPON_RAILGUN"),
    RPG             = GetHashKey("WEAPON_RPG"),
    RAYMINIGUN      = GetHashKey("WEAPON_RAYMINIGUN"),

    -- LMGs
    COMBATMG     = GetHashKey("WEAPON_COMBATMG"),
    COMBATMG_MK2 = GetHashKey("WEAPON_COMBATMG_MK2"),
    GUSENBERG    = GetHashKey("WEAPON_GUSENBERG"),
    MG           = GetHashKey("WEAPON_MG"),
    RAYCARBINE   = GetHashKey("WEAPON_RAYCARBINE"),

    -- Snipers
    HEAVYSNIPER       = GetHashKey("WEAPON_HEAVYSNIPER"),
    HEAVYSNIPER_MK2   = GetHashKey("WEAPON_HEAVYSNIPER_MK2"),
    MARKSMANRIFLE     = GetHashKey("WEAPON_MARKSMANRIFLE"),
    MARKSMANRIFLE_MK2 = GetHashKey("WEAPON_MARKSMANRIFLE_MK2"),
    SNIPERRIFLE       = GetHashKey("WEAPON_SNIPERRIFLE"),

    -- Throwables
    BALL         = GetHashKey("WEAPON_BALL"),
    BZGAS        = GetHashKey("WEAPON_BZGAS"),
    FLARE        = GetHashKey("WEAPON_FLARE"),
    GRENADE      = GetHashKey("WEAPON_GRENADE"),
    MOLOTOV      = GetHashKey("WEAPON_MOLOTOV"),
    PIPEBOMB     = GetHashKey("WEAPON_PIPEBOMB"),
    PROXMINE     = GetHashKey("WEAPON_PROXMINE"),
    SNOWBALL     = GetHashKey("WEAPON_SNOWBALL"),
    STICKYBOMB   = GetHashKey("WEAPON_STICKYBOMB"),
    SMOKEGRENADE = GetHashKey("WEAPON_SMOKEGRENADE"),
}

-- For human display
WeaponNames = {
    [Weapons.DAGGER]        = "Dagger",
    [Weapons.BAT]           = "Bat",
    [Weapons.BOTTLE]        = "Bottle",
    [Weapons.CROWBAR]       = "Crowbar",
    [Weapons.FLASHLIGHT]    = "Flashlight",
    [Weapons.GOLFCLUB]      = "Golf Club",
    [Weapons.HAMMER]        = "Hammer",
    [Weapons.HATCHET]       = "Hatchet",
    [Weapons.KNUCKLE]       = "Brass Knuckle",
    [Weapons.KNIFE]         = "Knife",
    [Weapons.MACHETE]       = "Machete",
    [Weapons.SWITCHBLADE]   = "Switchblade",
    [Weapons.NIGHTSTICK]    = "Baton",
    [Weapons.WRENCH]        = "Wrench",
    [Weapons.BATTLEAXE]     = "Axe",
    [Weapons.POOLCUE]       = "Pool Cue",
    [Weapons.STONE_HATCHET] = "Stone Hatchet",

    [Weapons.PISTOL]         = "Pistol",
    [Weapons.PISTOL_MK2]     = "Advanced Pistol",
    [Weapons.COMBATPISTOL]   = "Combat Pistol",
    [Weapons.APPISTOL]       = "Automatic Pistol",
    [Weapons.STUNGUN]        = "Stun Gun",
    [Weapons.PISTOL50]       = "Desert Eagle",
    [Weapons.SNSPISTOL]      = "SNS Pistol",
    [Weapons.SNSPISTOL_MK2]  = "Advanced SNS Pistol",
    [Weapons.HEAVYPISTOL]    = "Heavy Pistol",
    [Weapons.VINTAGEPISTOL]  = "Vintage Pistol",
    [Weapons.FLAREGUN]       = "Flare Gun",
    [Weapons.MARKSMANPISTOL] = "Marksman Pistol",
    [Weapons.REVOLVER]       = "Revolver",
    [Weapons.REVOLVER_MK2]   = "Advanced Revolver",
    [Weapons.DOUBLEACTION]   = "Double Action Revolver",
    [Weapons.RAYPISTOL]      = "Laser Pistol",

    [Weapons.MICROSMG]      = "Micro SMG",
    [Weapons.SMG]           = "SMG",
    [Weapons.SMG_MK2]       = "Advanced SMG",
    [Weapons.ASSAULTSMG]    = "Assault SMG",
    [Weapons.COMBATPDW]     = "Combat PDW",
    [Weapons.MACHINEPISTOL] = "Machine Pistol",
    [Weapons.MINISMG]       = "Mini SMG",

    [Weapons.PUMPSHOTGUN]     = "Pump Shotgun",
    [Weapons.PUMPSHOTGUN_MK2] = "Advanced Pump Shotgun",
    [Weapons.SAWNOFFSHOTGUN]  = "Sawed-off Shotgun",
    [Weapons.ASSAULTSHOTGUN]  = "Assault Shotgun",
    [Weapons.BULLPUPSHOTGUN]  = "Bullpup Shotgun",
    [Weapons.MUSKET]          = "Musket",
    [Weapons.HEAVYSHOTGUN]    = "Heavy Shotgun",
    [Weapons.DBSHOTGUN]       = "Double Barrel Shotgun",
    [Weapons.AUTOSHOTGUN]     = "Automatic Shotgun",

    [Weapons.ASSAULTRIFLE]       = "Assault Rifle",
    [Weapons.ASSAULTRIFLE_MK2]   = "Advanced Assault Rifle",
    [Weapons.CARBINERIFLE]       = "Carbine Rifle",
    [Weapons.CARBINERIFLE_MK2]   = "Advanced Carbine Rifle",
    [Weapons.ADVANCEDRIFLE]      = "Advanced Rifle",
    [Weapons.SPECIALCARBINE]     = "Special Carbine",
    [Weapons.SPECIALCARBINE_MK2] = "Advanced Special Carbine",
    [Weapons.BULLPUPRIFLE]       = "Bullpup Rifle",
    [Weapons.BULLPUPRIFLE_MK2]   = "Advanced Bullpup Rifle",
    [Weapons.COMPACTRIFLE]       = "Compact Rifle",

    [Weapons.COMPACTLAUNCHER] = "Compact Launcher",
    [Weapons.FIREWORK]        = "Firework Launcher",
    [Weapons.GRENADELAUNCHER] = "Grenade Launcher",
    [Weapons.HOMINGLAUNCHER]  = "Homing Launcher",
    [Weapons.MINIGUN]         = "Minigun",
    [Weapons.RAILGUN]         = "Railgun",
    [Weapons.RPG]             = "RPG",
    [Weapons.RAYMINIGUN]      = "Widowmaker",

    [Weapons.COMBATMG]     = "Combat MG",
    [Weapons.COMBATMG_MK2] = "Advanced Combat MG",
    [Weapons.GUSENBERG]    = "Gusenberg",
    [Weapons.MG]           = "Machine Gun",
    [Weapons.RAYCARBINE]   = "Unholy Hellbringer",

    [Weapons.HEAVYSNIPER]       = "Heavy Sniper",
    [Weapons.HEAVYSNIPER_MK2]   = "Advanced Heavy Sniper",
    [Weapons.MARKSMANRIFLE]     = "Marksman Rifle",
    [Weapons.MARKSMANRIFLE_MK2] = "Advanced Marksman Rifle",
    [Weapons.SNIPERRIFLE]       = "Sniper Rifle",

    [Weapons.BALL]         = "Ball",
    [Weapons.BZGAS]        = "Nerve Gas",
    [Weapons.FLARE]        = "Flare",
    [Weapons.GRENADE]      = "Grenade",
    [Weapons.MOLOTOV]      = "Molotov",
    [Weapons.PIPEBOMB]     = "Pipe Bomb",
    [Weapons.PROXMINE]     = "Proximity Mine",
    [Weapons.SNOWBALL]     = "Snowball",
    [Weapons.STICKYBOMB]   = "Sticky Bomb",
    [Weapons.SMOKEGRENADE] = "Tear Gas",
}

-- Machine readable i.e. image names
WeaponLabels = {
    [Weapons.DAGGER]        = "dagger",
    [Weapons.BAT]           = "bat",
    [Weapons.BOTTLE]        = "bottle",
    [Weapons.CROWBAR]       = "crowbar",
    [Weapons.FLASHLIGHT]    = "flashlight",
    [Weapons.GOLFCLUB]      = "golfclub",
    [Weapons.HAMMER]        = "hammer",
    [Weapons.HATCHET]       = "hatchet",
    [Weapons.KNUCKLE]       = "knuckle",
    [Weapons.KNIFE]         = "knife",
    [Weapons.MACHETE]       = "machete",
    [Weapons.SWITCHBLADE]   = "switchblade",
    [Weapons.NIGHTSTICK]    = "nightstick",
    [Weapons.WRENCH]        = "wrench",
    [Weapons.BATTLEAXE]     = "battleaxe",
    [Weapons.POOLCUE]       = "poolcue",
    [Weapons.STONE_HATCHET] = "stone_hatchet",

    [Weapons.PISTOL]         = "pistol",
    [Weapons.PISTOL_MK2]     = "pistol_mk2",
    [Weapons.COMBATPISTOL]   = "combatpistol",
    [Weapons.APPISTOL]       = "appistol",
    [Weapons.STUNGUN]        = "stungun",
    [Weapons.PISTOL50]       = "pistol50",
    [Weapons.SNSPISTOL]      = "snspistol",
    [Weapons.SNSPISTOL_MK2]  = "snspistol_mk2",
    [Weapons.HEAVYPISTOL]    = "heavypistol",
    [Weapons.VINTAGEPISTOL]  = "vintagepistol",
    [Weapons.FLAREGUN]       = "flaregun",
    [Weapons.MARKSMANPISTOL] = "marksmanpistol",
    [Weapons.REVOLVER]       = "revolver",
    [Weapons.REVOLVER_MK2]   = "revolver_mk2",
    [Weapons.DOUBLEACTION]   = "doubleaction",
    [Weapons.RAYPISTOL]      = "raypistol",

    [Weapons.MICROSMG]      = "microsmg",
    [Weapons.SMG]           = "smg",
    [Weapons.SMG_MK2]       = "smg_mk2",
    [Weapons.ASSAULTSMG]    = "assaultsmg",
    [Weapons.COMBATPDW]     = "combatpdw",
    [Weapons.MACHINEPISTOL] = "machinepistol",
    [Weapons.MINISMG]       = "minismg",

    [Weapons.PUMPSHOTGUN]     = "pumpshotgun",
    [Weapons.PUMPSHOTGUN_MK2] = "pumpshotgun_mk2",
    [Weapons.SAWNOFFSHOTGUN]  = "sawnoffshotgun",
    [Weapons.ASSAULTSHOTGUN]  = "assaultshotgun",
    [Weapons.BULLPUPSHOTGUN]  = "bullpupshotgun",
    [Weapons.MUSKET]          = "musket",
    [Weapons.HEAVYSHOTGUN]    = "heavyshotgun",
    [Weapons.DBSHOTGUN]       = "dbshotgun",
    [Weapons.AUTOSHOTGUN]     = "autoshotgun",

    [Weapons.ASSAULTRIFLE]       = "assaultrifle",
    [Weapons.ASSAULTRIFLE_MK2]   = "assaultrifle_mk2",
    [Weapons.CARBINERIFLE]       = "carbinerifle",
    [Weapons.CARBINERIFLE_MK2]   = "carbinerifle_mk2",
    [Weapons.ADVANCEDRIFLE]      = "advancedrifle",
    [Weapons.SPECIALCARBINE]     = "specialcarbine",
    [Weapons.SPECIALCARBINE_MK2] = "specialcarbine_mk2",
    [Weapons.BULLPUPRIFLE]       = "bullpuprifle",
    [Weapons.BULLPUPRIFLE_MK2]   = "bullpuprifle_mk2",
    [Weapons.COMPACTRIFLE]       = "compactrifle",

    [Weapons.COMPACTLAUNCHER] = "compactlauncher",
    [Weapons.FIREWORK]        = "firework",
    [Weapons.GRENADELAUNCHER] = "grenadelauncher",
    [Weapons.HOMINGLAUNCHER]  = "hominglauncher",
    [Weapons.MINIGUN]         = "minigun",
    [Weapons.RAILGUN]         = "railgun",
    [Weapons.RPG]             = "rpg",
    [Weapons.RAYMINIGUN]      = "rayminigun",

    [Weapons.COMBATMG]     = "combatmg",
    [Weapons.COMBATMG_MK2] = "combatmg_mk2",
    [Weapons.GUSENBERG]    = "gusenberg",
    [Weapons.MG]           = "mg",
    [Weapons.RAYCARBINE]   = "raycarbine",

    [Weapons.HEAVYSNIPER]       = "heavysniper",
    [Weapons.HEAVYSNIPER_MK2]   = "heavysniper_mk2",
    [Weapons.MARKSMANRIFLE]     = "marksmanrifle",
    [Weapons.MARKSMANRIFLE_MK2] = "marksmanrifle_mk2",
    [Weapons.SNIPERRIFLE]       = "sniperrifle",

    [Weapons.BALL]         = "ball",
    [Weapons.BZGAS]        = "bzgas",
    [Weapons.FLARE]        = "flare",
    [Weapons.GRENADE]      = "grenade",
    [Weapons.MOLOTOV]      = "molotov",
    [Weapons.PIPEBOMB]     = "pipebomb",
    [Weapons.PROXMINE]     = "proxmine",
    [Weapons.SNOWBALL]     = "snowball",
    [Weapons.STICKYBOMB]   = "stickybomb",
    [Weapons.SMOKEGRENADE] = "smokegrenade",
}
