Weapons = {
    -- Melee
    DAGGER        = GetHashKey("WEAPON_DAGGER"),
    BAT           = GetHashKey("WEAPON_BAT"),
    BOTTLE        = GetHashKey("WEAPON_BOTTLE"),
    CROWBAR       = GetHashKey("WEAPON_CROWBAR"),
    FLASHLIGHT    = GetHashKey("WEAPON_FLASHLIGHT"),
    GOLFCLUB      = GetHashKey("WEAPON_GOLFCLUB"),
    HAMMER        = GetHashKey("WEAPON_HAMMER"),
    HATCHET       = GetHashKey("WEAPON_HATCHET"),
    KNUCKLE       = GetHashKey("WEAPON_KNUCKLE"),
    KNIFE         = GetHashKey("WEAPON_KNIFE"),
    MACHETE       = GetHashKey("WEAPON_MACHETE"),
    SWITCHBLADE   = GetHashKey("WEAPON_SWITCHBLADE"),
    NIGHTSTICK    = GetHashKey("WEAPON_NIGHTSTICK"),
    WRENCH        = GetHashKey("WEAPON_WRENCH"),
    BATTLEAXE     = GetHashKey("WEAPON_BATTLEAXE"),
    POOLCUE       = GetHashKey("WEAPON_POOLCUE"),
    STONE_HATCHET = GetHashKey("WEAPON_STONE_HATCHET"),

    -- Handguns
    PISTOL         = GetHashKey("WEAPON_PISTOL"),
    PISTOL_MK2     = GetHashKey("WEAPON_PISTOL_MK2"),
    COMBATPISTOL   = GetHashKey("WEAPON_COMBATPISTOL"),
    APPISTOL       = GetHashKey("WEAPON_APPISTOL"),
    STUNGUN        = GetHashKey("WEAPON_STUNGUN"),
    PISTOL50       = GetHashKey("WEAPON_PISTOL50"),
    SNSPISTOL      = GetHashKey("WEAPON_SNSPISTOL"),
    SNSPISTOL_MK2  = GetHashKey("WEAPON_SNSPISTOL_MK2"),
    HEAVYPISTOL    = GetHashKey("WEAPON_HEAVYPISTOL"),
    VINTAGEPISTOL  = GetHashKey("WEAPON_VINTAGEPISTOL"),
    FLAREGUN       = GetHashKey("WEAPON_FLAREGUN"),
    MARKSMANPISTOL = GetHashKey("WEAPON_MARKSMANPISTOL"),
    REVOLVER       = GetHashKey("WEAPON_REVOLVER"),
    REVOLVER_MK2   = GetHashKey("WEAPON_REVOLVER_MK2"),
    DOUBLEACTION   = GetHashKey("WEAPON_DOUBLEACTION"),
    RAYPISTOL      = GetHashKey("WEAPON_RAYPISTOL"),
    --CERAMICPISTOL  = GetHashKey("WEAPON_CERAMICPISTOL"), -- Exist in some docs but can't find in game
    --NAVYREVOLVER   = GetHashKey("WEAPON_NAVYREVOLVER"),
    --GADGETPISTOL   = GetHashKey("WEAPON_GADGETPISTOL"),
    --STUNGUN_MP     = GetHashKey("WEAPON_STUNGUN_MP"),

    -- Submachine Guns
    MICROSMG        = GetHashKey("WEAPON_MICROSMG"),
    SMG             = GetHashKey("WEAPON_SMG"),
    SMG_MK2         = GetHashKey("WEAPON_SMG_MK2"),
    ASSAULTSMG      = GetHashKey("WEAPON_ASSAULTSMG"),
    COMBATPDW       = GetHashKey("WEAPON_COMBATPDW"),
    MACHINEPISTOL   = GetHashKey("WEAPON_MACHINEPISTOL"),
    MINISMG         = GetHashKey("WEAPON_MINISMG"),
    RAYCARBINE      = GetHashKey("WEAPON_RAYCARBINE"),

    -- Shotguns
    PUMPSHOTGUN     = GetHashKey("WEAPON_PUMPSHOTGUN"),
    PUMPSHOTGUN_MK2 = GetHashKey("WEAPON_PUMPSHOTGUN_MK2"),
    SAWNOFFSHOTGUN  = GetHashKey("WEAPON_SAWNOFFSHOTGUN"),
    ASSAULTSHOTGUN  = GetHashKey("WEAPON_ASSAULTSHOTGUN"),
    BULLPUPSHOTGUN  = GetHashKey("WEAPON_BULLPUPSHOTGUN"),
    MUSKET          = GetHashKey("WEAPON_MUSKET"),
    HEAVYSHOTGUN    = GetHashKey("WEAPON_HEAVYSHOTGUN"),
    DBSHOTGUN       = GetHashKey("WEAPON_DBSHOTGUN"),
    AUTOSHOTGUN     = GetHashKey("WEAPON_AUTOSHOTGUN"),
    --COMBATSHOTGUN   = GetHashKey("WEAPON_COMBATSHOTGUN"), -- Exist in some docs but can't find in game

    -- Assault Rifles
    ASSAULTRIFLE       = GetHashKey("WEAPON_ASSAULTRIFLE"),
    ASSAULTRIFLE_MK2   = GetHashKey("WEAPON_ASSAULTRIFLE_MK2"),
    CARBINERIFLE       = GetHashKey("WEAPON_CARBINERIFLE"),
    CARBINERIFLE_MK2   = GetHashKey("WEAPON_CARBINERIFLE_MK2"),
    ADVANCEDRIFLE      = GetHashKey("WEAPON_ADVANCEDRIFLE"),
    SPECIALCARBINE     = GetHashKey("WEAPON_SPECIALCARBINE"),
    SPECIALCARBINE_MK2 = GetHashKey("WEAPON_SPECIALCARBINE_MK2"),
    BULLPUPRIFLE       = GetHashKey("WEAPON_BULLPUPRIFLE"),
    BULLPUPRIFLE_MK2   = GetHashKey("WEAPON_BULLPUPRIFLE_MK2"),
    COMPACTRIFLE       = GetHashKey("WEAPON_COMPACTRIFLE"),
    --MILITARYRIFLE      = GetHashKey("WEAPON_MILITARYRIFLE"), -- Exist in some docs but can't find in game
    --HEAVYRIFLE         = GetHashKey("WEAPON_HEAVYRIFLE"),
}
