services:
  fivem:
    image: brice/tsrp-fivem:latest
    stdin_open: false
    network_mode: "host"
    tty: false
    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"
      - "40125:40125"
    volumes:
      - type: bind
        source: ./data/txData
        target: /fivem/fxserver/txData
      - type: bind
        source: ./cfg
        target: /fivem/server-data/config
      - type: bind
        source: ./vendor
        target: /fivem/server-data/resources/[vendor]
