-- Determines what weapons fit into which "slots" for the purposes of the inventory equipment screen.
WeaponSlots = {
    ["Pistol"] = {
        Weapons.PISTOL,
        Weapons.PISTOL_MK2,
        Weapons.COMBATPISTOL,
        Weapons.APPISTOL,
        Weapons.STUNGUN,
        Weapons.PISTOL50,
        Weapons.SNSPISTOL,
        Weapons.SNSPISTOL_MK2,
        Weapons.HEAVYPISTOL,
        Weapons.VINTAGEPISTOL,
        Weapons.FLAREGUN,
        Weapons.MARKSMANPISTO,
        Weapons.REVOLVER,
        Weapons.REVOLVER_MK2,
        Weapons.DOUBLEACTION,
        Weapons.RAYPISTOL
    },
    ["SMG/MG"] = {
        Weapons.MICROSMG,
        Weapons.SMG,
        Weapons.SMG_MK2,
        Weapons.ASSAULTSMG,
        Weapons.COMBATPDW,
        Weapons.MACHINEPISTOL,
        Weapons.MINISMG,
        Weapons.COMBATMG,
        Weapons.COMBATMG_MK2,
        Weapons.GUSENBERG,
        Weapons.MG,
        Weapons.RAYCARBINE,
    },
    ["Rifle"] = {
        Weapons.ASSAULTRIFLE,
        Weapons.ASSAULTRIFLE_MK2,
        Weapons.CARBINERIFLE,
        Weapons.CARBINERIFLE_MK2,
        Weapons.ADVANCEDRIFLE,
        Weapons.SPECIALCARBINE,
        Weapons.SPECIALCARBINE_MK2,
        Weapons.BULLPUPRIFLE,
        Weapons.BULLPUPRIFLE_MK2,
        Weapons.COMPACTRIFLE,
    },
    ["Sniper"] = {
        Weapons.HEAVYSNIPER,
        Weapons.HEAVYSNIPER_MK2,
        Weapons.MARKSMANRIFLE,
        Weapons.MARKSMANRIFLE_MK2,
        Weapons.SNIPERRIFLE,
    },
    ["Melee"] = {
        Weapons.DAGGER,
        Weapons.BAT,
        Weapons.BOTTLE,
        Weapons.CROWBAR,
        Weapons.FLASHLIGHT,
        Weapons.GOLFCLUB,
        Weapons.HAMMER,
        Weapons.HATCHET,
        Weapons.KNUCKLE,
        Weapons.KNIFE,
        Weapons.MACHETE,
        Weapons.SWITCHBLADE,
        Weapons.NIGHTSTICK,
        Weapons.WRENCH,
        Weapons.BATTLEAXE,
        Weapons.POOLCUE,
        Weapons.STONE_HATCHET,
    },
    ["Shotgun"] = {
        Weapons.PUMPSHOTGUN,
        Weapons.PUMPSHOTGUN_MK2,
        Weapons.SAWNOFFSHOTGUN,
        Weapons.ASSAULTSHOTGUN,
        Weapons.BULLPUPSHOTGUN,
        Weapons.MUSKET,
        Weapons.HEAVYSHOTGUN,
        Weapons.DBSHOTGUN,
        Weapons.AUTOSHOTGUN,
    },
    ["Heavy"] = {
        Weapons.COMPACTLAUNCHER,
        Weapons.FIREWORK,
        Weapons.GRENADELAUNCHER,
        Weapons.HOMINGLAUNCHER,
        Weapons.MINIGUN,
        Weapons.RAILGUN,
        Weapons.RPG,
        Weapons.RAYMINIGUN,
    },
    ["Throwable"] = {
        Weapons.BALL,
        Weapons.BZGAS,
        Weapons.FLARE,
        Weapons.GRENADE,
        Weapons.MOLOTOV,
        Weapons.PIPEBOMB,
        Weapons.PROXMINE,
        Weapons.SNOWBALL,
        Weapons.STICKYBOMB,
        Weapons.SMOKEGRENADE,
    }
}
